### ISSUE TITLE
Release 2.4

### ISSUE THREAD

**Issue by thijstriemstra** [sybrenstuvel/flickrapi#103]
@sybrenstuvel can you release a new version on pypi?

**Comment by sybrenstuvel** [comment]
I'm not so thrilled to have 236450a1de965d35d624e368a9b99979e24c9065, 2c2b4f8a541ed54e4af03d570d2bd322cac0557d, 1421f4b389b0fa9e85a7b3e62768e443ef5a637f, and e89c0e9e38708fe4d5c35b0dafb081b697358ddc as separate commits in the master branch. It would have been trivial to squash them into a single commit that did all of those things properly in one go. Please be a bit more careful what you push to the master branch.

I can't release 2.3.2 now, since there is no mention of the changes in CHANGELOG.md about 2.3.1 and 2.3.2. Can you add that too? I can do it too, but as you've probably noticed (and got annoyed by, most likely), I have very little time to work on flickrapi at the moment, so it may take a while.

**Comment by thijstriemstra** [comment]
Wow wow wo wow, say what?

> It would have been trivial to squash them into a single commit that did all of those things properly in one go. Please be a bit more careful what you push to the master branch.

If you remember correctly it was you that approved the pull request and merged it to master, not me. I asked you for feedback and eventually you merged it without squashing the full pull request. If you would've wanted me to do that, you could've asked me, no? Accusing me of being careless comes across as quite rude to be honest with you @sybrenstuvel.

![screenshot from 2018-01-09 17-12-57](https://user-images.githubusercontent.com/305679/34730792-b3ea0ee6-f560-11e7-9491-404606a64836.png)

**Comment by sybrenstuvel** [comment]
I had no intention to be rude, my apologies. My mind is in 100 different places right now, I judged too quickly. I'm very thankful for all the help!

**Comment by thijstriemstra** [comment]
Opened #107
